spring:
  main:
    banner-mode: off
#  http:
#    converters:
#      preferred-json-mapper: gson

  ## Spring Datasource passed in via environment variables
  datasource:
    url:
    username:
    password:

  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      ## Hibernate Properties
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ## This is important
        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: validate

server:
  shutdown: graceful

springdoc:
  show-actuator: true
  swagger-ui:
    doc-expansion: none
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"

flyway:
  baselineOnMigrate: false

logging:
  config: classpath:log4j2.xml
  level:
    root: ERROR
    org:
      example: TRACE
      apache:
        catalina: WARN
        coyote: WARN
      springframework: WARN