--CREATE TABLE roles (
--    ID bigint(20) NOT NULL AUTO_INCREMENT,
--    NAME varchar(50) NOT NULL,
--    DESCRIPTION varchar(255),
--    PRIMARY KEY (ID),
--    UNIQUE KEY UK_name (NAME)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--CREATE TABLE statuses (
--    ID bigint(20) NOT NULL AUTO_INCREMENT,
--    NAME varchar(50) NOT NULL,
----    DESCRIPTION varchar(255),
--    PRIMARY KEY (ID),
--    UNIQUE KEY UK_name (NAME)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
--CREATE TABLE workspace_types (
--    ID bigint(20) NOT NULL AUTO_INCREMENT,
--    NAME varchar(50) NOT NULL,
--    DESCRIPTION varchar(255),
--    PRIMARY KEY (ID),
--    UNIQUE KEY UK_name (NAME)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    UUID binary(16) NOT NULL,
    STATUS varchar(10) NOT NULL,
    DATE_CREATED timestamp(0) DEFAULT NOW(0),
    PROFILE_ID bigint(20) NULL DEFAULT NULL,
    LOGIN_ID bigint(20) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_uuid (UUID),
    UNIQUE KEY UK_profileId (PROFILE_ID),
    UNIQUE KEY UK_loginId (LOGIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_profiles (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_email (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE logins (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    USERNAME varchar(100) NOT NULL,
    PASSWORD_HASH varchar(255) NOT NULL,
    LAST_SUCCESSFUL_LOGIN timestamp(3) NULL DEFAULT NULL,
    LAST_FAILED_LOGIN timestamp(3) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_username (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE memberships (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    USER_UUID binary(16) NOT NULL,
    WORKSPACE_UUID binary(16) NOT NULL,
    ROLE_ID bigint(20) NOT NULL,
    DATE_CREATED timestamp(3) DEFAULT NOW(3),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_membership (USER_UUID, WORKSPACE_UUID, ROLE_ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE workspaces (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    UUID binary(16) NOT NULL,
    NAME varchar(50) NOT NULL,
    STATUS varchar(10) NOT NULL,
    WORKSPACE_TYPE bigint(20) NOT NULL,
    DATE_CREATED timestamp(3) DEFAULT NOW(3),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_name (NAME),
    UNIQUE KEY UK_uuid (UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE users ADD FOREIGN KEY (PROFILE_ID) REFERENCES user_profiles(ID);
ALTER TABLE users ADD FOREIGN KEY (LOGIN_ID) REFERENCES logins(ID);

ALTER TABLE memberships ADD FOREIGN KEY (USER_UUID) REFERENCES users(UUID);
ALTER TABLE memberships ADD FOREIGN KEY (WORKSPACE_UUID) REFERENCES workspaces(UUID);
--ALTER TABLE memberships ADD FOREIGN KEY (ROLE_ID) REFERENCES roles(ID);
--ALTER TABLE users ADD FOREIGN KEY (STATUS) REFERENCES statuses(ID);
--ALTER TABLE workspaces ADD FOREIGN KEY (STATUS) REFERENCES statuses(ID);
--ALTER TABLE workspaces ADD FOREIGN KEY (TYPE) REFERENCES workspace_types(ID);

--INSERT INTO statuses (name) VALUES ('ACTIVE'), ('SUSPENDED'), ('DELETED');